Fix urlcam.py to retreive scan images from the PiZeroCam
romi/romiscanner pull request #4
Opened 2020-08-17 14:38 UTC by jlegrand62

Close #3

2020-08-17 14:41 UTC, jlegrand62 commented on romiscanner/urlcam.py
> +        _ = requests.get(self.url + "/scan.jpg")  # update the picture
Make a `get` request to update the image by calling `grab` from the `picamera` module in `picamera_server.py`.

2020-08-17 14:45 UTC, jlegrand62 commented on romiscanner/urlcam.py
> +        _ = requests.get(self.url + "/scan.jpg")  # update the picture
Code for `picamera_server.py` can be found on the ROMI documentation [here](https://docs.romi-project.eu/Scanner/build/picamera_setup/#camera-serve-python-code).

2020-09-02 14:47 UTC, hanappe commented on romiscanner/urlcam.py
> +        data = imageio.imread(self.url + "/scan.jpg")  # download it
Could you try line 65 only, without the preliminary call in line 64?

2020-09-02 14:48 UTC, hanappe requested changes
See comment on line 65

2020-09-10 17:33 UTC, merged